knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Sortable/bootstrap_v4_sortable.html.twig'
