knp_paginator:
    page_range: 5          # how many pages to show on each side of current page
    default_options:
        page_name: page    # query parameter name
        sort_field_name: sort
        sort_direction_name: direction
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'